# -*- coding: utf-8 -*-
"""Indentation&statement&variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiRIWemLyH68-SM6rOMIq89WOUB_59d2

#Indentation:
Indentation means leaving spaces at the beginning of a line of code.

Python uses indentation to know which lines of code belong together.

Unlike many other programming languages, Python does not use { } (curly braces) to create blocks. Instead, it uses indentation.
Why is Indentation Important?

Indentation helps Python understand:

Which statements belong to an if block.
Which statements belong to a loop (for or while).
Which statements belong to a function.
Where a block of code starts and ends.

Without proper indentation, Python cannot understand your program and gives an error.
"""

age = 20

if age >= 18:
    print("You are eligible to vote.")

print("Program Ended")

"""#Statements:
A statement is a single instruction that tells Python to do something.

"""

a=20         #assigment statement
print(a)     #print statement

if 18>=age:                   #Conditional statement
    print("elig")

for i in range():             #loop statement

import math                  #import statement

"""#Variables:
A variable is a name used to store data (a value) in memory.
--->can store
int
float
bool
tuple
list
str
"""

a=10 #a-->variable
     #10-->value