# -*- coding: utf-8 -*-
"""Keywords&identifiers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMwrpbx2lkTQnmO5TG0UY4z5mP7VsiZ6

#what is keywords in python
keywords are reserved words  in python.
1.we cannot use has function names.
2.And variable names
3.keywords case sentive
#in python 3.13-35 keywords
#in python 3.39-36 keywords
"""

import keyword
print(keyword.kwlist)

"""#what is identifiers
An identifier is the name you give to a variable, function, class, module, or any other object in Python.

"""

name="i love python" #name is identifier
print(name)

def greet(name):
  print(f"hii {name}")       #in fun greet is ide

greet("mani")

class Student:                #student is ide
  pass

"""#comments
Comments are notes written inside a Python program to explain the code. Python ignores comments when running the program.
1.single-line
#this single line comment
2.mulit-line comments
''' or '''
''' this is my
python programm.
this is my c
programm'''


"""