# -*- coding: utf-8 -*-
"""numpy_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQV0J85bKIxxr60kEk-0_cyuuAbyIjc9
"""

!pip install numpy

#creating 1D Array
import numpy as np
list1=np.array([10,30,49,59])
print(list1)

#2D Array
import numpy as np
list1=np.array([[1,4,5,7]
               ,[4,5,6,7]])
print(list1)
print(list1.ndim) #number of dime
print(list1.shape) #rows and clo
print(list1.size) #size
print(list1.dtype) #datatype

'''Creating Special Arrays
Zeros'''
import numpy as np
list1=np.zeros((2,5))
print(list1)

#Identity Matrix
import numpy as np
list1=np.eye(3)
print(list1)

