# -*- coding: utf-8 -*-
"""recursion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOTEFn17Jk9lv1MFZAtsrbUTr4zaZtiZ
"""

#factorial problem
def fact(n):
    #this is base case if n is 0 return 1
    if n==0:
        return 1
    else:
        #rec case n!=n*(n-1)
        return n*fact(n-1)

print(fact(5))