# -*- coding: utf-8 -*-
"""Types_of_Exception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZpNo7lu8jrhS5wrYFVpsw57ivMWSrLY
"""

#ZeroDivisionError
a=10
b=0
print(a/b)

#valueError
num=int("mani")
print(num)

#Type_error
a=10
b="20"
print(a+b)

#IndexError
num=[10,20,30]
print(num[5])

student = {
    "name":"Rahul",
    "age":20
}

print(student["marks"])

